#!/bin/bash

command_type="deactivate"
root_dir='/root/capstone/'

echo $command_type


#change python, package 
python3 ${root_dir}env.py deactivate base


#change prompt 
prompt=$(python3 ${root_dir}env.py deactivate prompt)
export PS1=${prompt}" "
	

